import Head from 'next/head'
import Image from 'next/image'
import { Inter } from '@next/font/google'
import Header from '../components/Header'
import Skills from '../components/Skills'
import Footer from '../components/Footer'
import Box from '../components/SocialBox'
import SocialBox from '../components/SocialBox'
import userdata from "../userData"
import React,{useState,useEffect} from 'react'
import { Coin } from 'react-bootstrap-icons'
export default function Home() {
  //  alert(userdata.container.bgcolor);
  if (typeof window === 'object') {
    const changes = document.body;
    changes.style.backgroundColor = userdata.backgroundColor;
    changes.style.color = userdata.container.textColor;
    changes.style.fontFamily = userdata.fontFamily;
  }

  function Timer() {
    const [count, setCount] = useState(0);
  
    useEffect(() => {
      setTimeout(() => {
        setCount((count) => count + 1);
      }, 1000);
      // alert(count);
    });
  }

Timer();

  return (
    
    <div className="h-screen pt-4 from-indigo-500 mainDiv rounded-xl">
      <Head>
        <title>Link Type || Link Type</title>
        <meta name="description" content="Generated by next app" />
        <link rel="icon" href="/favicon.ico" />
        <style>
          @import url('https://fonts.googleapis.com/css2?family=Barlow:ital,wght@1,700&family=Cedarville+Cursive&family=Karla&family=Poppins&family=Roboto&display=swap');
        </style>
      </Head>

      <div className='mainDiv'>
        <Header />
        <Skills />
        <SocialBox />
        <Footer />
      </div>
    </div>
  )
};
